language: go

go:
  - 1.17

services:
  - docker

before_install:
  - echo "minhtom1510" | docker login -u "minhtd5" --password-stdin
  - go mod vendor
  - sudo apt-get update && sudo apt-get install -y docker-compose

script:
  - go build -o ./bin/app ./app/service
  - chmod +x ./bin/app
  - docker-compose up -d
  - ./bin/app/service

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: bash .docker_push
  on:
    branch: master
