language: go
go:
  - 1.17

before_install:
  - echo "minhtom1510" | docker login -u "minhtd5" --password-stdin
  #  - docker-compose up
  - go mod vendor

script:
  - go build -o ./bin/app ./app/service
  - chmod +x ./bin/app
  - docker-compose up -d
  - ./bin/app/service

after_success:
  # Báo cáo coverage code hoặc các công việc khác sau khi thành công (tuỳ chọn)
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: bash .docker_push
  on:
    branch: master
