CREATE TABLE OWNER
(
    OWNER_ID     INT PRIMARY KEY,
    TENANT_ID    INT          NOT NULL,
    OWNER_NAME   VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(20)  NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   VARCHAR(100),
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY   VARCHAR(100)
);

CREATE TABLE BOOKING
(
    BOOKING_ID         INT PRIMARY KEY,
    SUB_SPORT_FIELD_ID INT          NOT NULL,
    BOOKING_DATE       DATE         NOT NULL,
    BOOKER_NAME        VARCHAR(255) NOT NULL,
    BOOKER_PHONE       VARCHAR(20)  NOT NULL,
    START_TIME         TIME         NOT NULL,
    END_TIME           TIME         NOT NULL,
    BOOKING_STATUS     VARCHAR(50)  NOT NULL,
    DEPOSIT_STATUS     VARCHAR(50)  NOT NULL,
    CREATED_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY         VARCHAR(100),
    UPDATED_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY         VARCHAR(100)
);

CREATE TABLE REVENUE
(
    REVENUE_ID    INT PRIMARY KEY,
    BOOKING_ID    INT            NOT NULL,
    TOTAL_REVENUE DECIMAL(10, 2) NOT NULL,
    CREATED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY    VARCHAR(100),
    UPDATED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY    VARCHAR(100)

);

