server:
  host: 0.0.0.0
  port: 8081
  timeout:
    server: "1200s"
    read: "1200s"
    write: "1200s"
    idle: "1200s"


XApiKey: "akfndkwfnklswnmljkfnmswljkfnwjlkngfjwenj"
database:
    host: mysql-242e090-ducminhtong1510-d931.a.aivencloud.com
    port: 21440
    user: avnadmin
    pass: AVNS_PRb_ApuInzGLCBw_ux7
    dbName: convertor
#    host: localhost
#    port: 3306
#    user: root
#    pass: tongminh1510
#    dbName: EDUDBTEST

    # postgresql
#    host: localhost
#    port: 5432
#    user: kong
#    pass: kongpass
#    dbName: kong

#    postgresql aiven
#    host: pg-2aaeaeca-ducminhtong1510-d931.b.aivencloud.com
#    port: 21440
#    user: avnadmin
#    pass: AVNS_UiWf4Eh9vQU7u5b5R98
#    dbName: defaultdb

#  host: 10.96.210.203
#  port: 3306
#  user: fall2324w20g6
#  pass: qwertyuiop
#  dbName: fall2324w20g6_tmp

flashClient:
  root: "http://34.100.254.97:8083/"
  get-course-revenue-by-course-id: "b/v1/flash/hello"
  get-yearly-revenue: "b/v1/flash/yearly-revenue"

redisClient:
  addr: "10.56.158.182:6379"
  password: ""
  db: 0


