server:
  host: 0.0.0.0
  port: 8081
  timeout:
    server: "30s"
    read: "15s"
    write: "10s"
    idle: "5s"


XApiKey: "akfndkwfnklswnmljkfnmswljkfnwjlkngfjwenj"
database:
    host: mysql-242e090-ducminhtong1510-d931.a.aivencloud.com
    port: 21440
    user: avnadmin
    pass: AVNS_PRb_ApuInzGLCBw_ux7
    dbName: defaultdb
#    host: localhost
#    port: 3306
#    user: root
#    pass: tongminh1510
#    dbName: EDUDBTEST
#  host: 10.96.210.203
#  port: 3306
#  user: fall2324w20g6
#  pass: qwertyuiop
#  dbName: fall2324w20g6_tmp

flashClient:
  root: "http://35.200.240.181:8080/"
  get-course-revenue-by-course-id: "b/v1/flash/hello"
  get-yearly-revenue: "b/v1/flash/yearly-revenue"

redisClient:
  addr: "10.56.158.182:6379"
  password: ""
  db: 0


