name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.12

      - name: Build Go app
        run: go build -o ./bin/app ./app/service/main.go

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build --tag minhtd5/batman:v1 .
          docker push minhtd5/batman:v1


      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker to Google Cloud Registry
        run: gcloud auth configure-docker

#      - name: Authenticate with gcloud
#        run: gcloud auth login

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Build and Push Docker Image
        env:
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev
          docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/batman/batman:v1 .
          docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/batman/batman:v1
          
      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY_FILE }}

      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud container clusters get-credentials flash --region asia-south1
          sed -i "s/GCP_PROJECT_ID/GCP_PROJECT_ID/g" resources.yaml
          kubectl apply -f resources.yaml

#      - name: Create JSON key file
#        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /tmp/gcp-key.json
#
#      - name: Authenticate with service account key
#        run: |
#          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json
#          gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
#
#      - name: Configure kubectl
#        run: |
#          gcloud container clusters get-credentials flash --region asia-south1 --project practical-block-419106
#
#      - name: Deploy to GKE
#        run: |
#          kubectl set image deployment/nginx batman=minhtd5/batman:v1
#          kubectl rollout status deployment/nginx
#          gcloud config set project practical-block-419106
#          gcloud config set compute/zone asia-south1
#          gcloud container clusters get-credentials flash
#          gcloud container clusters update flash --update-addons=HttpLoadBalancing=ENABLED
#          gcloud container clusters update flash --update-addons=HorizontalPodAutoscaling=ENABLED
#          curl -LO https://raw.githubusercontent.com/minhtd15/batman/master/resources.yaml
#          kubectl apply -f resources.yaml
#          kubectl apply -f https://raw.githubusercontent.com/minhtd15/batman/master/resources.yaml




