name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.12

      - name: Build Go app
        run: go build -o ./bin/app ./app/service/main.go

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: minhttd15
          password: minhtom1510

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build --tag minhtd5/batman:v1 .
          docker push minhtd5/batman:v1

