name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.12

      - name: Build Go app
        run: go build -o ./bin/app ./app/service/main.go

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build --tag minhtd5/batman:v1 .
          docker push minhtd5/batman:v1


      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker to Google Cloud Registry
        run: gcloud auth configure-docker

#      - name: Authenticate with gcloud
#        run: gcloud auth login

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Create JSON key file
        run: echo "${{ secrets.JSON }}" > /tmp/gcp-key.json

      - name: Authenticate with service account key
        run: gcloud auth activate-service-account --key-file /tmp/gcp-key.json

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials flash --region asia-south1 --project practical-block-419106

      - name: Deploy to GKE
        run: |
          kubectl apply -f https://raw.githubusercontent.com/minhtd15/batman/master/resources.yaml
#          kubectl set image deployment/nginx batman=minhtd5/batman:v1
#          kubectl rollout status deployment/nginx


